# Generated by Django 3.1 on 2020-08-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200815_2200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
