# Generated by Django 3.1 on 2020-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200816_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='author_default.jpeg', upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_default.jpeg', upload_to='book_images'),
        ),
    ]
